name: 'Upload RPMs'
description: 'Upload RPMs in a standardized way for oVirt. It must be '
inputs:
  directory:
    description: 'Which directory to upload'
    required: true
    default: 'exported-artifacts'
runs:
  using: "composite"
  steps:
    - name: Install createrepo_c if needed
      shell: bash
      run: which createrepo_c || dnf install -y createrepo_c
    - name: Create DNF repository if needed
      shell: bash
      run: test -d ${{ inputs.directory }}/repodata || createrepo_c ${{ inputs.directory }}
    - name: Get distro suffix
      id: eval
      shell: bash
      run: echo "::set-output name=distro::$(rpm --eval %{?dist} | cut -d '.' -f 2)"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rpm-${{ steps.eval.outputs.distro }}
        path: ${{ inputs.directory }}
