name: Self-test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  selftest:
    name: Self-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upload and build artifacts
        uses: ./
        with:
          script: test-source/rpm.sh
          distro: stream8
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts-stream8
          path: downloaded
      - name: Check if the test.rpm is there
        run:
          test -f downloaded/test-0-0.x86_64.rpm
